### ISSUE TITLE
eval.py error

### ISSUE THREAD

**Issue by navarmn** [igormq/asr-study#6]
Using TensorFlow backend.
WARNING:tensorflow:From /mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/.env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:1029: calling reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
[<tf.Tensor 'Reshape_21:0' shape=(?, ?, 28) dtype=float32>, <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x7fc13c0a7b90>, <tf.Tensor 'inputs_length:0' shape=(?, ?) dtype=int32>]
WARNING:tensorflow:From /mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/.env/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py:1108: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Traceback (most recent call last):
  File "eval.py", line 74, in <module>
    test_flow = data_gen.flow_from_fname(args.dataset, datasets=args.subset)
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/datasets/dataset_generator.py", line 72, in flow_from_fname
    for dataset in datasets]
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/datasets/dataset_generator.py", line 111, in flow_from_h5_group
    mode=self.mode)
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/datasets/dataset_generator.py", line 258, in __init__
    inputs = h5group['inputs']
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/mnt/Work/Projects/2018-Locktec-SAVOZ/general/asr-study/.env/local/lib/python2.7/site-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'inputs' doesn't exist)"

**Comment by igormq** [comment]
Hi @navarmn ,

The warning says that you are using a newer version of Tensorflow (this code is really old by now, haha).

Please, check yout hdf5 file and observe if a group called `inputs` was created.
